events {
    worker_connections 1024;
}

http {

    server_tokens off;

    upstream inventory_backend {
        server app:3000;
    }

    server {
        listen 80;
        server_name _;

        # Security Headers
        add_header X-Frame-Options "SAMEORIGIN" always;
        add_header X-Content-Type-Options "nosniff" always;
        add_header Referrer-Policy "strict-origin-when-cross-origin" always;
        add_header Permissions-Policy "camera=(), microphone=(), geolocation=()" always;

        location / {
            proxy_pass http://inventory_backend;

            proxy_http_version 1.1;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /nginx-health {
            access_log off;

            return 200 "nginx healthy\n";

            add_header Content-Type text/plain;
        }
    }
}
