#!/bin/sh

set -e

mysql -u root -p"${MYSQL_ROOT_PASSWORD}" <<EOSQL

REVOKE ALL PRIVILEGES, GRANT OPTION
FROM '${MYSQL_USER}'@'%';

GRANT SELECT, INSERT, UPDATE, DELETE
ON \`${MYSQL_DATABASE}\`.*
TO '${MYSQL_USER}'@'%';

FLUSH PRIVILEGES;

EOSQL
