#!/bin/bash

set -e

mysql -u root -p"${MYSQL_ROOT_PASSWORD}" <<EOSQL

CREATE USER IF NOT EXISTS 'exporter'@'%'
IDENTIFIED BY '${MYSQL_EXPORTER_PASSWORD}'
WITH MAX_USER_CONNECTIONS 3;

GRANT PROCESS, REPLICATION CLIENT, SELECT
ON *.*
TO 'exporter'@'%';

FLUSH PRIVILEGES;

EOSQL
